config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :budget_categories
  resources :budget_items

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources  :budgets
    end
  end

  get 'home/index'

  get 'greetings/hello'
  


  resources :budgets
   # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root 'budgets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget_item.rb
class BudgetItem < ApplicationRecord
  has_and_belongs_to_many :Budgets, optional: true, :join_table => 'budgets_budget_items'
  belongs_to :BudgetCategory, optional: true
end

app/controllers/api/v1/budget_items_controller.rb
module Api
  module V1
    class BudgetItemsController < ApplicationController
      before_action :set_budget, only: [:show, :edit, :update, :destroy]
      respond_to :json
    
      # GET /budget_items
      # GET /budget_items.json
      def index
        resond_with BudgetItem.all
      end
    
      # GET /budget_items/1
      # GET /budget_items/1.json
      def show
      end
    
      # GET /budget_items/new
      def new
        @budget_item = BudgetItem.new
        @BCats = BudgetCategory.all.map{|bc| [bc.Name, bc.id]}
      end
      
      # GET /budget_items/1/edit
      def edit
        @BCats = BudgetCategory.all.map{|bc| [bc.Name, bc.id]}
      end
    
      # POST /budget_items
      # POST /budget_items.json
      def create
        @budget_item = BudgetItem.new(budget_item_params)
    
    
        respond_to do |format|
          if @budget_item.save
            format.html { redirect_to @budget_item, notice: 'Budget item was successfully created.' }
            format.json { render :show, status: :created, location: @budget_item }
          else
            format.html { render :new }
            format.json { render json: @budget_item.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /budget_items/1
      # PATCH/PUT /budget_items/1.json
      def update
        respond_to do |format|
          if @budget_item.update(budget_item_params)
            format.html { redirect_to @budget_item, notice: 'Budget item was successfully updated.' }
            format.json { render :show, status: :ok, location: @budget_item }
          else
            format.html { render :edit }
            format.json { render json: @budget_item.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /budget_items/1
      # DELETE /budget_items/1.json
      def destroy
        @budget_item.destroy
        respond_to do |format|
          format.html { redirect_to budget_items_url, notice: 'Budget item was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_budget_item
          @budget_item = BudgetItem.find(params[:id])
        end
    
        # Never trust parameters from the scary internet, only allow the white list through.
        def budget_item_params
          params.fetch(:budget_item, {}).permit(:amount, :BudgetCategory_id, :DueDate, :StartDate, :EndDate, :IsReocurring, :IsCollection)
        end
    end
  end
end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController
  before_action :set_budget_item, only: [:show, :edit, :update, :destroy]

  # GET /budget_items
  # GET /budget_items.json
  def index
    @budget_items = BudgetItem.all
  end

  # GET /budget_items/1
  # GET /budget_items/1.json
  def show
  end

  # GET /budget_items/new
  def new
    @budget_item = BudgetItem.new
    @BCats = BudgetCategory.all.map{|bc| [bc.Name, bc.id]}
  end
  
  # GET /budget_items/1/edit
  def edit
    @BCats = BudgetCategory.all.map{|bc| [bc.Name, bc.id]}
  end

  # POST /budget_items
  # POST /budget_items.json
  def create
    @budget_item = BudgetItem.new(budget_item_params)


    respond_to do |format|
      if @budget_item.save
        format.html { redirect_to @budget_item, notice: 'Budget item was successfully created.' }
        format.json { render :show, status: :created, location: @budget_item }
      else
        format.html { render :new }
        format.json { render json: @budget_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_items/1
  # PATCH/PUT /budget_items/1.json
  def update
    respond_to do |format|
      if @budget_item.update(budget_item_params)
        format.html { redirect_to @budget_item, notice: 'Budget item was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget_item }
      else
        format.html { render :edit }
        format.json { render json: @budget_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_items/1
  # DELETE /budget_items/1.json
  def destroy
    @budget_item.destroy
    respond_to do |format|
      format.html { redirect_to budget_items_url, notice: 'Budget item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_item
      @budget_item = BudgetItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_item_params
      params.fetch(:budget_item, {}).permit(:amount, :BudgetCategory_id, :DueDate, :StartDate, :EndDate, :IsReocurring, :IsCollection)
    end
end

app/helpers/budget_items_helper.rb
module BudgetItemsHelper
end

app/views/budget_items/_form.html.erb
<%= form_for(budget_item) do |f| %>
  <% if budget_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget_item.errors.count, "error") %> prohibited this budget_item from being saved:</h2>

      <ul>
      <% budget_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class='table table-striped'>
    <tr>
      <th>Category</th>
      <td><%= f.select(:BudgetCategory_id ,@BCats) %> </td>
    </tr>
    <tr>
      <th>Amount</th>
      <td><%= f.text_field(:amount)%></td>
    </tr>
    <tr>
      <th>Due Date</th>
      <td><%= f.date_field :DueDate, class: 'datepicker' %></td>
    </tr>
    <tr>
      <th>Is this item reoccuring?</th>
      <td><%= f.check_box :IsReocurring, {},"true", "false" %></td>
    </tr>
    <tr>
      <th>Start Date</th>
      <td><%= f.date_field :StartDate, class: 'datepicker' %></td>
    </tr>
    <tr>
      <th>End Date</th>
      <td><%= f.date_field :EndDate, class: 'datepicker' %></td>
    </tr>
    <tr>
      <th>Is this item a collection?</th>
      <td><%= f.check_box :IsCollection, {}, "true", "false" %></td>
    </tr>

  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budget_items/edit.html.erb
<h1>Editing Budget Item</h1>

<%= render 'form', budget_item: @budget_item %>

<%= link_to 'Show', @budget_item %> |
<%= link_to 'Back', budget_items_path %>

app/views/budget_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budget Items</h1>

<table class='table table-stripped'>
  <thead>
    <tr>
      <th>Category Name</th><th>Amount</th><th>Due Date</th><th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @budget_items.each do |budget_item| %>
      <tr>
        <td><%= budget_item.BudgetCategory.Name %></td>
        <td><%= number_to_currency(budget_item.amount) %></td>
        <td><%= budget_item.DueDate %></td>
        <td><%= link_to 'Show', budget_item %></td>
        <td><%= link_to 'Edit', edit_budget_item_path(budget_item) %></td>
        <td><%= link_to 'Destroy', budget_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget Item', new_budget_item_path %>

app/views/budget_items/new.html.erb
<h1>New Budget Item</h1>

<%= render 'form', budget_item: @budget_item %>

<%= link_to 'Back', budget_items_path %>

app/views/budget_items/show.html.erb
<p id="notice"><%= notice %></p>

<table class='table'>
  <thead><th>Category</th><th>Amount</th><th>Due Date</th><th>Start Date</th><th>End Date</th><th>Is Reoccuring</th><th>Is Collection</th><th>Date Created</th><th>Last Updated</th></thead>
  <tr>
    <td><%= @budget_item.BudgetCategory.Name%></td>
    <td><%= number_to_currency(@budget_item.amount) %></td>
    <td><%= @budget_item.DueDate %></td>
    <td><%= @budget_item.StartDate %></td>
    <td><%= @budget_item.EndDate %></td>
    <td><%= @budget_item.IsReocurring %></td>
    <td><%= @budget_item.IsCollection %></td>
    <td><%= @budget_item.created_at%> </td>
    <td><%= @budget_item.updated_at%> </td>
    <td><%= link_to 'Edit', edit_budget_item_path(@budget_item) %> </td>

  </tr>
</table>

<%= link_to 'Back', budget_items_path %>