config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :budget_categories
  resources :budget_items

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources  :budgets
    end
  end

  get 'home/index'

  get 'greetings/hello'
  


  resources :budgets
   # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root 'budgets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord

has_and_belongs_to_many :BudgetItems, :join_table => 'budgets_budget_items'

end

app/controllers/api/v1/budgets_controller.rb
module Api
  module V1
    class BudgetsController < ApplicationController
      respond_to :json

      def index
        respond_with Budget.all
      end
      def show
        respond_with Budget.find(params[:id])
      end

      def create
        respond_with Budget.create(params[:product])
      end

      def update
        respond_with Budget.update(params[:id], params[:product])
      end

      def destroy
        respond_with Budget.destroy(params[:id])
      end
    end
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
    
    respond_to do |format|
      format.html
      format.json {render json: @budgets}
    end
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
      @budget = Budget.find(params[:id])

      @balArray = Array.new

      i = 0
      newBal = @budget.StartingBalance

      @budget.BudgetItems.each do |b|

        if(b.BudgetCategory.IsDebit)
          newBal -= b.amount
        else
          newBal += b.amount
        end
        puts(newBal)
        #add new balance to array
      @balArray.push newBal
        i += 1
      end

  end


  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)
    @budget.CurrentBalance = @budget.StartingBalance
    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.fetch(:budget, {}).permit(:Title, :StartingBalance)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_for(budget) do |f| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>


  <% end %>
  <table summary="Budget Form Fields" class="table table-striped">
    <tr>
      <th>Title</th>
      <td><%= f.text_field(:Title) %></td>
    </tr>
    <tr>
      <th>Starting Balance</th>
      <td><%= f.text_field(:StartingBalance) %></td>
    </tr>
    

  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>
<div ng-controller="BudgetCtrlJs as b">
  {{b.FirstName}} {{b.LastName}}
  
  <table class="table table-stripped">
    <thead>
      <th>Title</th>
      <th>Current Balance</th>
      <th>Options</th>
    </thead>
    
    <tr ng-repeat="bud in b.budgets">
      <td><a href="budgets/{{bud.id}}">{{bud.Title}}</a></td>
      <td>{{bud.CurrentBalance | currency:"$"}}</td>     
      <td><a href="budgets/{{bud.id}}/edit">Edit</a></td>
      
    
    </tr>
    </tbody>
  </table>
<br>

<%= link_to 'New Budget', new_budget_path %>

</div>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>
<table class='table'>
  <thead><th>Name</th><th>Starting Balance</th><th>Current Balance</th><th>Created</th><th>Updated</th><th>Options</th></thead>
  <tr>
    <td><%= @budget.Title %></td>
    <td><%= number_to_currency(@budget.StartingBalance) %></td>
    <td><%= number_to_currency(@budget.CurrentBalance) %></td>
    <td><%= @budget.created_at%> </td>
    <td><%= @budget.updated_at%> </td>
    <td><%= link_to 'Edit', edit_budget_path(@budget) %> </td>


  </tr>
</table>

<%= link_to 'Back', budgets_path %>

<table class='table table-stripped'>
  <thead>

    <th>Category</th><th>Due Date</th><th>Amount</th><th>Balance</th>
  <thead>
  <%i = 0%>
  <% @budget.BudgetItems.each do |bi|%>
      <tr>
        <td><%= bi.BudgetCategory.Name%></td>
        <td><%= bi.StartDate%></td>
        <td><%= number_to_currency(bi.amount)%></td>
        <td><%= number_to_currency(@balArray[i])%></td>
        <% i += 1%>
    </tr>
  <%end%>
</table>