config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :budget_categories
  resources :budget_items

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources  :budgets
    end
  end

  get 'home/index'

  get 'greetings/hello'
  


  resources :budgets
   # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root 'budgets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget_category.rb
class BudgetCategory < ApplicationRecord
has_many :BudgetItems

end

app/controllers/budget_categories_controller.rb
class BudgetCategoriesController < ApplicationController
  before_action :set_budget_category, only: [:show, :edit, :update, :destroy]

  # GET /budget_categories
  # GET /budget_categories.json
  def index
    @budget_categories = BudgetCategory.all
  end

  # GET /budget_categories/1
  # GET /budget_categories/1.json
  def show
  end

  # GET /budget_categories/new
  def new
    @budget_category = BudgetCategory.new
  end

  # GET /budget_categories/1/edit
  def edit
  end

  # POST /budget_categories
  # POST /budget_categories.json
  def create
    @budget_category = BudgetCategory.new(budget_category_params)

    respond_to do |format|
      if @budget_category.save
        format.html { redirect_to @budget_category, notice: 'Budget category was successfully created.' }
        format.json { render :show, status: :created, location: @budget_category }
      else
        format.html { render :new }
        format.json { render json: @budget_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_categories/1
  # PATCH/PUT /budget_categories/1.json
  def update
    respond_to do |format|
      if @budget_category.update(budget_category_params)
        format.html { redirect_to @budget_category, notice: 'Budget category was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget_category }
      else
        format.html { render :edit }
        format.json { render json: @budget_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_categories/1
  # DELETE /budget_categories/1.json
  def destroy
    @budget_category.destroy
    respond_to do |format|
      format.html { redirect_to budget_categories_url, notice: 'Budget category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_category
      @budget_category = BudgetCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_category_params
      params.fetch(:budget_category, {}).permit(:Name, :IsDebit, :sort)
    end
end

app/helpers/budget_categories_helper.rb
module BudgetCategoriesHelper
end

app/views/budget_categories/_form.html.erb
<%= form_for(budget_category) do |f| %>
  <% if budget_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget_category.errors.count, "error") %> prohibited this budget_category from being saved:</h2>

      <ul>
      <% budget_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <th>Name</th>
      <td><%= f.text_field(:Name)%></td>
    </tr>
    <tr>
      <th>Is this a debit?</th>
      <td><%= f.check_box(:IsDebit, :default => true)%></td>
    </tr>
    <tr>
      <th>Sort</th>
      <td><%= f.text_field(:sort)%></td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budget_categories/edit.html.erb
<h1>Editing Budget Category</h1>

<%= render 'form', budget_category: @budget_category %>

<%= link_to 'Show', @budget_category %> |
<%= link_to 'Back', budget_categories_path %>

app/views/budget_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budget Categories</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Sort<th>Category Name</th><th>Is Debit</th><th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @budget_categories.each do |budget_category| %>
      <tr>
        <td><%= budget_category.sort %></td>
        <td><%= budget_category.Name %></td>
        <td><%= budget_category.IsDebit %></td>
        <td><%= link_to 'Show', budget_category %></td>
        <td><%= link_to 'Edit', edit_budget_category_path(budget_category) %></td>
        <td><%= link_to 'Destroy', budget_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget Category', new_budget_category_path %>

app/views/budget_categories/new.html.erb
<h1>New Budget Category</h1>

<%= render 'form', budget_category: @budget_category %>

<%= link_to 'Back', budget_categories_path %>

app/views/budget_categories/show.html.erb
<p id="notice"><%= notice %></p>
<table class='table'>
  <thead><th>Sort</th><th>Category Name</th><th>Is Debit?</th><th>Options</th>
  <tr>
    <td><%= @budget_category.sort %></td>
    <td><%= @budget_category.Name %></td>
    <td><%= @budget_category.IsDebit %></td>
    <td><%= link_to 'Edit', edit_budget_category_path(@budget_category) %> </td>
  </tr>
</table>

<%= link_to 'Back', budget_categories_path %>